In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
path = "drive/My Drive/Colab Notebooks/dart/opendart/data/"

# Library

In [4]:
from xml.etree.ElementTree import parse
import pandas as pd
# import json

# Data Load

In [6]:
tree = parse(path + "CORPCODE.xml")
root = tree.getroot()
df = []
for element in root.findall("list"):
    corp_code = element.findtext("corp_code")
    corp_name = element.findtext("corp_name")
    stock_code = element.findtext("stock_code")
    df.append({"corp_code":corp_code, "corp_name":corp_name, "stock_code":stock_code})

In [7]:
df = pd.DataFrame(df)

In [8]:
print(df.shape)
df

(82008, 3)

      corp_code          corp_name stock_code
0      00434003                 다코
1      00434456               일산약품
2      00430964              굿앤엘에스
3      00432403               한라판지
4      00388953  크레디피아제이십오차유동화전문회사
...         ...                ...        ...
82003  00809553           강진참사랑의료원
82004  01499308                 유강
82005  00531777               영무건설
82006  01032495                 펍지
82007  00685962               송도파워

[82008 rows x 3 columns]

### Stock 코드가 있는 회사만 8만 -> 3천

In [9]:
print(df.shape)
list=[True if item != " " else False for item in df['stock_code']]
df = df[list]
print(df.shape)

(82008, 3)
(3234, 3)

In [11]:
df.tail()

      corp_code corp_name stock_code
81993  00220622      서호전기     065710
81994  00173351        삼진     032750
81995  00186559     콤텍시스템     031820
81997  00476036   에프엔에스테크     083500
81998  00899556      제룡산업     147830

In [12]:
df = df.reset_index(drop=True)
df

     corp_code corp_name stock_code
0     00260985      한빛네트     036720
1     00264529      엔플렉스     040130
2     00358545    동서정보기술     055000
3     00231567     애드모바일     032600
4     00247939       씨모스     037600
...        ...       ...        ...
3229  00220622      서호전기     065710
3230  00173351        삼진     032750
3231  00186559     콤텍시스템     031820
3232  00476036   에프엔에스테크     083500
3233  00899556      제룡산업     147830

[3234 rows x 3 columns]

In [13]:
df.to_csv(path + "corpcode3234.csv", index=False)

In [16]:
df2 = pd.read_csv(path + "corpcode3234.csv")
df2

      corp_code corp_name  stock_code
0        260985      한빛네트       36720
1        264529      엔플렉스       40130
2        358545    동서정보기술       55000
3        231567     애드모바일       32600
4        247939       씨모스       37600
...         ...       ...         ...
3229     220622      서호전기       65710
3230     173351        삼진       32750
3231     186559     콤텍시스템       31820
3232     476036   에프엔에스테크       83500
3233     899556      제룡산업      147830

[3234 rows x 3 columns]

In [17]:
temp = pd.read_csv(path + "corpcode3234.csv", converters=dict(corp_code=str))
temp.head()

  corp_code corp_name  stock_code
0  00260985      한빛네트       36720
1  00264529      엔플렉스       40130
2  00358545    동서정보기술       55000
3  00231567     애드모바일       32600
4  00247939       씨모스       37600

In [18]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3234 entries, 0 to 3233
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   corp_code   3234 non-null   object
 1   corp_name   3234 non-null   object
 2   stock_code  3234 non-null   int64
dtypes: int64(1), object(2)
memory usage: 75.9+ KB